exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]

pygments:   false
markdown:   redcarpet
auto:       true

#For Theme
shorttitle : 42
title: 42 Days with Rails

production_url : http://warm-light-3984.herokuapp.com/

author :
  name : Maya Osseiran
  email : oss.maya@gmail.com